#!/bin/bash

sudo usermod -u 500 www-data

cd /home/etouraille/src/simple-builder/container

sudo docker-compose kill
sudo docker-compose build

sudo docker-compose up -d

cd /home/etouraille/src/simple-builder

sudo chown -R etouraille:etouraille .

git fetch 
git rebase origin/master
git submodule update

cd /home/etouraille/src/simple-builder

sudo chown -R www-data:www-data .

key=$(docker exec -ti container_php_1 more /root/.ssh/id_rsa.pub)

grep "$key" /home/etouraille/.ssh/authorized_keys
if [ $? -ne 0 ];then
	echo "key added"
	echo $key >> /home/etouraille/.ssh/authorized_keys
else
	echo "key not added"
fi	